### ISSUE TITLE
Adding VCH to a project in Admiral leads to it getting added to a different project 

### ISSUE THREAD

**Issue by jitinkumar1994** [vmware/vic-product#2137] opened 2018-10-26 05:50 UTC
Bug Report Basic Information
----------------------------

REQUIRED:

- vCenter Server version: 6.5U2
- Embedded or external PSC: Embedded
- Filename of the OVA you deployed: vic-dev-v1.4.4-dev-6326-5874a1d2.ova
- How was the OVA deployed? (Flex client, HTML5 client, ovftool): ovftool
- Does the VIC appliance recieve configuration by DHCP? No, static
- What stage of the Appliance Lifecycle is the VIC appliance in? Application
- Attach the VIC appliance support bundle 
[vic_appliance_logs_2018-10-26-05-41-11.tar.gz](https://github.com/vmware/vic-product/files/2517852/vic_appliance_logs_2018-10-26-05-41-11.tar.gz)

- IP address of VIC appliance: 10.197.37.132

Bug Report Detailed Information
-------------------------------

- What operation was being performed when the failure was noticed?
    - Created a project : project-p01 through admiral UI -> Administration tab. 
    - While trying to add a VCH to this project through: Infrastructure -> + Container Host , the 
       operation is successful but the VCH gets added to default-project and not project-p01

- Additional Information:
    -VCH addition via REST Api works correctly.

**Comment by lgayatri** [comment] 2018-10-26 06:03
This is with VIC 1.4.4

**Comment by renmaosheng** [comment] 2018-10-26 06:09
Hi Lakshmi, is this a regression from 1.4.3?

**Comment by lgayatri** [comment] 2018-10-26 06:15
Hi Steven, Jitin is verifying if this is a regression. Will update asap.

**Comment by renmaosheng** [comment] 2018-10-26 06:41
I can successfully add vch to the new project, my vic appliance is 10.192.208.11

**Comment by jitinkumar1994** [comment] 2018-10-26 08:40
Observing the same behavior in 1.4.3

**Comment by lazarin** [comment] 2018-10-31 10:10
Hi @jitinkumar1994, we were not able to reproduce that with docker or vch hosts.
Can you verify these steps and then we can schedule a zoom session 
1 create a new project in Administration tab
2 from Home tab switch to the newly created project (upper left corner)
3 add a container host (vch or docker) - host should appear in container hosts view
4 verify that when you switch to other project host is not shown

we can schedule zoom session and see that live if needed

**Comment by jitinkumar1994** [comment] 2018-10-31 13:30
Hi @lazarin , I produced the error using the following steps and not with your procedure:
1) create a new project in Administration tab
2) Select the project you created in the Administration tab
3) Clicking on + CONTAINER HOST in the Infrastructure tab and providing VCH details
4) Refresh symbol appears and VCH is not seen on the infrastructure tab of the project but rather added to default-project

Admiral : vic-st-h2-183.eng.vmware.com:8282

If my procedure is the wrong way to add VCH to a project, I shall close this bug. Thank you @lazarin

**Comment by lazarin** [comment] 2018-10-31 13:53
Confirmed, it's reproducible. 
If I create a new project it is opened directly and when immediately add a host it's added to the right project. But if I go first to Home tab, select another project, then back to Administration, select the new project and add a host -> it is going to the default project.

@jitinkumar1994 thanks for reporting we will work on that one.

**Comment by zjs** [comment] 2019-01-29 00:50
@lazarin: Is this still a problem or can this issue be closed?

**Comment by lazarin** [comment] 2019-01-30 08:16
@zjs we'll check it and work on if still reproducible

**Comment by lazarin** [comment] 2019-02-05 07:08
with latest vic-dev image that's fixed, @AleksandrovaP has pushed a fix

**Closed** 2019-02-12 23:08 UTC
Labels: kind/defect, product/admiral, source/system-test
