### ISSUE TITLE
Document that after OVA upgrade there are duplicate VCHs in admiral

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-product#847] opened 2017-09-21 07:01 UTC
Post successful upgrade of OVA from 1.1.1 to 1.2.y , I am seeing duplicate VCHs as in the screenshot below:
```
root@vic-st-h2-186 [ /etc/vmware/upgrade ]# ./upgrade_1.1_to_1.2.sh
Getting password from harbor.cfg
Enter vCenter Server FQDN or IP: wdc-stvc3944-152-dhcp212.eng.vmware.com
Enter vCenter Administrator Username: administrator@vsphere.sgp.dbs.com
Enter vCenter Administrator Password:
If using an external PSC, enter the FQDN of the PSC instance (leave blank otherwise): wdc-stvc3944-152-dhcp211.eng.vmware.com
If using an external PSC, enter the PSC Admin Domain (leave blank otherwise): vsphere.sgp.dbs.com
Starting upgrade 2017-09-21 06:24:11 +0000 UTC
Preparing upgrade environment
Disabling and stopping Admiral and Harbor path startup
Finished preparing upgrade environment
Performing pre-upgrade checks
Starting Admiral upgrade
[=] Shutting down Harbor and Admiral
[=] Upgrade Admiral
Admiral migration complete
Archiving previous Admiral data
Cleaning up
Admiral upgrade complete
Starting Admiral
Updating Admiral configuration
Performing pre-upgrade checks
Starting Harbor upgrade
[=] Shutting down Harbor
[=] Migrating Harbor data
[=] Finished migrating Harbor data
[=] Migrating Harbor configuration
[=] Finished migrating Harbor configuration
[=] Importing project data into Admiral
[=] Finished importing project data into Admiral
[=] Mapping project data into Harbor
[=] Finished mapping project data into Harbor
Harbor upgrade complete
Starting Harbor
Enabling and starting Admiral and Harbor path startup
Upgrade script complete. Exiting.
```
![image](https://user-images.githubusercontent.com/25006749/30682431-46b75e72-9ec7-11e7-99db-74e7b11a0008.png)
Even placementzone got placed here.Newly added VCHs are not getting duplicated.

**Comment by lgayatri** [comment] 2017-09-21 07:03
[847.zip](https://github.com/vmware/vic-product/files/1320240/847.zip)

**Comment by gmuleshkov** [comment] 2017-09-21 07:54
This is expected behavior. In VIC 1.2 the data model is change compared to 1.1
Here I suppose that the case is the following:
1. Before upgrade there were 2 Placements pointing to the same Placement zone
2. After upgrade in this case a new placement is created in order to match the new relation between placement-> placement zone . In VIC 1.2 is it 1:1. In vic 1.1 the relation was one to many.
In VIC 1.2 the clusters are actually placement-zones.

**Comment by sergiosagu** [comment] 2017-09-21 07:57
Closing it as per @gmuleshkov 's comment.

**Comment by andrewtchin** [comment] 2017-09-21 16:16
@gmuleshkov @sergiosagu do we need to document that the user needs to manually remove these?
cc @stuclem

**Comment by stuclem** [comment] 2017-09-22 12:06
@gmuleshkov is it correct to say that

**Comment by sergiosagu** [comment] 2017-09-26 07:21
> is it correct to say that this occurs if you added the same VCH to two placement zones in 1.1.1?

@stuclem / @andrewtchin - That's correct. And if needed, the user can manually remove the duplicated ones.

**Comment by stuclem** [comment] 2017-09-27 14:38
@sergiosagu does it matter which one, or are they identical?

**Comment by stuclem** [comment] 2017-09-27 14:38
Reopening for doc.

**Comment by sergiosagu** [comment] 2017-09-27 14:41
@stuclem - It doesn't really matter as long as they belong to the same project. Leaving one instance per project will be enough.

**Comment by stuclem** [comment] 2017-09-27 14:44
OK thanks

**Comment by stuclem** [comment] 2017-09-27 16:05
@lgayatri can you please describe the steps that you took in 1.1.1 before the upgrade, that led to these duplicate VCHs appearing in 1.2? I cannot reproduce it. But that said, I don't really know much about placements, placement zones, and projects in Management Portal / Admiral 1.1, so I'm obviously doing something wrong in 1.1. Thanks!

**Comment by stuclem** [comment] 2017-09-27 17:37
@sergiosagu, I'm still trying to get my head around @gmuleshkov 's comment above, and placements in general. So, can you pleas help with the following questions?:

- In 1.1, a placement zone is a cluster of VCHs/Docker hosts. 
- In 1.1, a placement is .... what exactly? The association of a VCH/placement zone with a project?
- In 1.1, when you provision a container from a template, you provision it into a project. In this way it is deployed on the VCH/placement zone that is associated with that project, or potentially on one of several VCHs that are associated with that project. 
- In 1.2 is the concept of placements and placement zones invisible to the users, or completely replaced by the fact that you add VCHs directly to projects?
- Are Admiral 1.1 projects migrated into 1.2 projects, like Harbor 1.1 projects? I have never managed to make an Admiral 1.1 project that has migrated, probably because I don't create them properly in 1.1.
- If the idea of placement zones is completely gone in 1.2, do you have to manually reassign VCHs to projects after upgrading to 1.2, or do the project/VCH associations carry over into 1.2 projects? 

I am trying to understand how objects in 1.1 map to objects in 1.2, with a view to updating/expanding/improving https://vmware.github.io/vic-product/assets/files/html/1.2/vic_vsphere_admin/upgrade_data.html and describing what post-upgrade tasks have to be done manually. So, understanding (finally) how all of this works in 1.1 is definitely relevant to 1.2.

Thanks in advance!

**Comment by stuclem** [comment] 2017-09-28 07:30
@sergiosagu I added a new topic, [Tasks to Perform After Upgrading the vSphere Integrated Containers Appliance](https://github.com/stuclem/vic-product/blob/installupgrade121/docs/user_doc/vic_vsphere_admin/post_upgrade_tasks.md), in https://github.com/vmware/vic-product/pull/868/commits/3f6859ae6c2778fa450eb8d77373852661a0d1c4, which includes an item about these duplicate VCHs. Can you please take a look and comment in PR https://github.com/vmware/vic-product/pull/868? Thanks!

**Comment by stuclem** [comment] 2017-10-03 13:59
Reviewed by @sergiosagu via Slack.

**Closed by stuclem** 2017-10-03 13:59 UTC
Labels: component/admiral, component/ova, kind/user-doc, pub/vsphere
