### ISSUE TITLE
Can't download root cert

### ISSUE THREAD

**Issue by cuwab** [vmware/vic-product#1030] opened 2017-11-02 04:03 UTC
I am trying to install vSphere Integrated Containers 1.2 from the OVA but once connected to my VIC appliance I can't download root cert from Administration > Configuration
Any idea?

![capture](https://user-images.githubusercontent.com/33305546/32309316-e738350a-bfde-11e7-9867-aff526ef458e.PNG)

**Comment by andrewtchin** [comment] 2017-11-02 21:01
Maybe related to #821

**Comment by andrewtchin** [comment] 2017-11-02 21:42
Hi @cuwab is this VIC Appliance version 1.2 or 1.2.1?
Could you ssh into the appliance and provide the output of `journalctl -u harbor` and `journalctl -u admiral`?

**Comment by andrewtchin** [comment] 2017-11-02 21:44
Closing as duplicate of https://github.com/vmware/harbor/issues/3527
The logs of `journalctl -u harbor` may be helpful to the Harbor team and can be pasted in their issue

**Closed by andrewtchin** 2017-11-02 21:44 UTC
Labels: kind/customer-found, status/need-info, team/lifecycle
