### ISSUE TITLE
The getting started page of the 1.3 OVA references 1.2 documentation

### ISSUE THREAD

**Issue by zjs** [vmware/vic-product#1167] opened 2017-11-28 22:14 UTC
**VIC Product version:**

`vic-v1.3.0-rc2-2628-9e2a95b6.ova`

**Deployment details:**

N/A

**Steps to reproduce:**

Load the Getting Started page (on port 9443).

**Actual behavior:**

Documentation links refer to the 1.2 documentation

**Expected behavior:**

Documentation links refer to the 1.3 documentation

**Comment by andrewtchin** [comment] 2017-11-28 22:21
Dupe of #1081

**Closed by andrewtchin** 2017-11-28 22:21 UTC
Labels: team/lifecycle
