### ISSUE TITLE
Admiral logs are not getting updated on OVA

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-product#1124] opened 2017-11-22 06:08 UTC
@andrewtchin @mhagen-vmware @stuclem @sergiosagu 

There were few errors in Admiral and I wanted to check the logs. Checked  journalctl -u admiral.service , docker logs vic-admiral and docker logs <containerID of Admiral> and noticed that the logs did not get updated after Nov 16 10:27:39 .

As per https://vmware.github.io/vic-product/assets/files/html/1.2/vic_vsphere_admin/appliance_logs.html,  docker logs vic-admiral should provide the logs but that is not showing updated logs.

However the journalctl output says:
-- Logs begin at Tue 2017-11-14 00:30:25 UTC, end at Wed 2017-11-22 05:34:25 UTC. -- 
but there is no latest logging.

I found xenonHost.0.log in /storage/log/admiral which seems to record admiral activity. The file is 545MB.

Three issues here:
1. We should fix "docker logs vic-admiral" to get the latest admiral logs
2. If user should refer to xenonHost log in /storage/log/admiral for admiral logs, then can we zip the log file and use log rotation as single file with 545 MB is huge
3. Why does journalctl show partial logs

**Comment by andrewtchin** [comment] 2017-11-22 15:54
Admiral logs are now designed to be in /storage/log/admiral so docker logs is no longer used. What partial logs are present in journalctl -u admiral? When opening an issue for logging, please include the logs that you believe to be a problem.

**Comment by lgayatri** [comment] 2017-11-22 16:17
journalctl -u admiral complete log is pasted below:

```
-- Logs begin at Tue 2017-11-14 00:30:25 UTC, end at Wed 2017-11-22 16:15:58 UTC. --
Nov 14 00:34:13 vic-st-h2-132.eng.vmware.com systemd[1]: Started Admiral is a highly scalable and very lightweight Container Management platform for deploying and managing container based applicati
ons..
Nov 14 00:34:13 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: + '[' false = true ']'
Nov 14 00:34:13 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: + '[' x = x ']'
Nov 14 00:34:13 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: + MEMORY_OPTS='-Xmx768M -Xms768M -Xss256K -Xmn256M -XX:MaxMetaspaceSize=256m'
Nov 14 00:34:13 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: + CONFIG_FILES=/admiral/config/dist_configuration.properties
Nov 14 00:34:13 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: + '[' -f /configs/config.properties ']'
Nov 14 00:34:13 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: + CONFIG_FILES=/admiral/config/dist_configuration.properties,/configs/config.properties
Nov 14 00:34:13 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: + '[' x = x ']'
Nov 14 00:34:13 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: + XENON_PHOTON_MODEL_PROPS='-Dservice.document.version.retention.limit=50 -Dservice.document.version.retention.floor=10'
Nov 14 00:34:13 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: + JAVA_OPTS='-Ddcp.net.ssl.trustStore=/configs/trustedcertificates.jks -Ddcp.net.ssl.trustStorePassword=changeit -Dencryption.ke
y.file=/var/admiral/8282/encryption.key -Dinit.encryption.key.file=true -Xmx768M -Xms768M -Xss256K -Xmn256M -XX:MaxMetaspaceSize=256m'
Nov 14 00:34:13 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: + JAVA_OPTS='-Ddcp.net.ssl.trustStore=/configs/trustedcertificates.jks -Ddcp.net.ssl.trustStorePassword=changeit -Dencryption.ke
y.file=/var/admiral/8282/encryption.key -Dinit.encryption.key.file=true -Xmx768M -Xms768M -Xss256K -Xmn256M -XX:MaxMetaspaceSize=256m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/admiral/'
Nov 14 00:34:13 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: + PID=6
Nov 14 00:34:13 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: + wait 6
Nov 14 00:34:13 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: + java -Djava.util.logging.config.file=/admiral/config/logging.properties -Dconfiguration.properties=/admiral/config/dist_config
uration.properties,/configs/config.properties -Ddcp.net.ssl.trustStore=/configs/trustedcertificates.jks -Ddcp.net.ssl.trustStorePassword=changeit -Dencryption.key.file=/var/admiral/8282/encryption.
key -Dinit.encryption.key.file=true -Xmx768M -Xms768M -Xss256K -Xmn256M -XX:MaxMetaspaceSize=256m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/admiral/ -cp '/admiral/*:/admiral/lib/*:/etc/
xenon/dynamic-services/*' -Dservice.document.version.retention.limit=50 -Dservice.document.version.retention.floor=10 com.vmware.admiral.host.ManagementHost --bindAddress=0.0.0.0 --port=-1 --sandbo
x=/var/admiral/ --publicUri=https://10.197.37.132:8282/ --bindAddress=0.0.0.0 --port=-1 --authConfig=/configs/psc-config.properties --securePort=8282 --keyFile=/configs/server.key --certificateFile
=/configs/server.crt --startMockHostAdapterInstance=false
Nov 14 00:34:15 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
Nov 14 00:34:15 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: SLF4J: Defaulting to no-operation (NOP) logger implementation
Nov 14 00:34:15 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Nov 14 00:34:15 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: log4j:WARN No appenders could be found for logger (io.netty.util.internal.logging.InternalLoggerFactory).
Nov 14 00:34:15 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: log4j:WARN Please initialize the log4j system properly.
Nov 14 00:34:15 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Nov 16 05:54:24 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: [Fatal Error] :1:1: Content is not allowed in prolog.
Nov 16 05:54:24 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: [Fatal Error] :1:1: Content is not allowed in prolog.
Nov 16 05:54:24 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: [Fatal Error] :1:1: Content is not allowed in prolog.
Nov 16 05:54:24 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: [Fatal Error] :1:1: Content is not allowed in prolog.
Nov 16 05:54:24 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: [Fatal Error] :1:1: Content is not allowed in prolog.
Nov 16 05:54:24 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: [Fatal Error] :1:1: Content is not allowed in prolog.
Nov 16 05:54:24 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: [Fatal Error] :1:1: Content is not allowed in prolog.
Nov 16 05:54:24 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: [Fatal Error] :1:1: Content is not allowed in prolog.
Nov 16 05:54:31 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: [Fatal Error] :1:1: Content is not allowed in prolog.
Nov 16 05:54:41 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: [Fatal Error] :1:1: Content is not allowed in prolog.
Nov 16 05:54:51 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: [Fatal Error] :1:1: Content is not allowed in prolog.
Nov 16 05:54:52 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: [Fatal Error] :1:1: Content is not allowed in prolog.
Nov 16 10:27:04 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: [Fatal Error] :1:1: Content is not allowed in prolog.
Nov 16 10:27:04 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: [Fatal Error] :1:1: Content is not allowed in prolog.
Nov 16 10:27:06 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: [Fatal Error] :1:1: Content is not allowed in prolog.
Nov 16 10:27:06 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: [Fatal Error] :1:1: Content is not allowed in prolog.
Nov 16 10:27:07 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: [Fatal Error] :1:1: Content is not allowed in prolog.
Nov 16 10:27:07 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: [Fatal Error] :1:1: Content is not allowed in prolog.
Nov 16 10:27:07 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: [Fatal Error] :1:1: Content is not allowed in prolog.
Nov 16 10:27:12 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: [Fatal Error] :1:1: Content is not allowed in prolog.
Nov 16 10:27:14 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: [Fatal Error] :1:1: Content is not allowed in prolog.
Nov 16 10:27:23 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: [Fatal Error] :1:1: Content is not allowed in prolog.
Nov 16 10:27:34 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: [Fatal Error] :1:1: Content is not allowed in prolog.
Nov 16 10:27:39 vic-st-h2-132.eng.vmware.com start_admiral.sh[1688]: [Fatal Error] :1:1: Content is not allowed in prolog.
```
root@vic-st-h2-132 [ /storage/log/admiral ]# date
Wed Nov 22 16:17:16 UTC 2017

Please feel free to SSH to 10.197.37.132- root/Admin!23 for any further details.

**Comment by andrewtchin** [comment] 2017-11-22 16:36
I logged in and I believe this is functioning correctly. The logs in journalctl are for the service starting, while the application logs are in `/storage/log/admiral`
The `Content is not allowed in prolog.` seems to be a java error coming from Admiral. 
@sergiosagu can you confirm that this is expected behavior?

**Comment by sergiosagu** [comment] 2017-11-23 14:03
> I logged in and I believe this is functioning correctly. The logs in journalctl are for the service starting, while the application logs are in `/storage/log/admiral`

That's the expected behavior I'd say.

> The `Content is not allowed in prolog.` seems to be a java error coming from Admiral.

Not sure exactly why this is happening yet, but the same issue is reported in https://github.com/vmware/vic-product/issues/1110
Thus I'm closing this one.

**Closed by sergiosagu** 2017-11-23 14:03 UTC
Labels: component/admiral, component/ova, status/need-info, team/lifecycle
