### ISSUE TITLE
Add a UI plugin install section support.md

### ISSUE THREAD

**Issue by jak-atx** [vmware/vic-product#1349] opened 2018-01-29 17:47 UTC
**Details:**
Add a UI plugin install section support.md document

i.e...
-list of common issues and..
-what steps user should try to resolve issue
-what info should user gather to help us in debugging the problem

**Comment by andrewtchin** [comment] 2018-02-15 15:06
duplicate of https://github.com/vmware/vic-ui/issues/343

**Closed by andrewtchin** 2018-02-15 15:06 UTC
