### ISSUE TITLE
appliance.iso upload is slow

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-product#1577] opened 2018-04-09 14:56 UTC
Bug Report Basic Information
----------------------------

REQUIRED:

- vCenter Server version: 6.5 U1
- Embedded or external PSC: Embedded
- Filename of the OVA you deployed: vic-dev-v1.4.0-dev-4398-3c5cd51a.ova
- Does the VIC appliance recieve configuration by DHCP? Static
- What stage of the Appliance Lifecycle is the VIC appliance in? vic create machine is taking too long 
  https://github.com/vmware/vic-product/blob/master/installer/docs/SUPPORT.md#appliance-lifecycle
- Attach the VIC appliance support bundle (e.g. vic_appliance_logs_2018-01-01-00-01-00.tar.gz)
  https://github.com/vmware/vic-product/blob/master/installer/docs/SUPPORT.md#appliance-support-bundle
  Note: The support bundle may contain private information. If you are not comfortable with posting this publicly, please contact VMware GSS.

Bug Report Detailed Information
-------------------------------

- What operation was being performed when the failure was noticed?
vic machine create is too slow and did not complete since 4 hours. Tried the same on two different Datastores and saw the same issue.

@mdubya66 @mhagen-vmware @andrewc-vmware 
[vic_appliance_logs_2018-04-09-14-55-14.tar.gz](https://github.com/vmware/vic-product/files/1890393/vic_appliance_logs_2018-04-09-14-55-14.tar.gz)

**Comment by lgayatri** [comment] 2018-04-09 14:57
```time="2018-04-09T10:52:25-04:00" level=info msg="Uploading appliance.iso. Progress: 5.42%"
time="2018-04-09T10:52:28-04:00" level=info msg="Uploading appliance.iso. Progress: 5.42%"
time="2018-04-09T10:52:31-04:00" level=info msg="Uploading appliance.iso. Progress: 5.42%"
time="2018-04-09T10:52:34-04:00" level=info msg="Uploading appliance.iso. Progress: 5.42%"
time="2018-04-09T10:52:37-04:00" level=info msg="Uploading appliance.iso. Progress: 5.42%"
time="2018-04-09T10:52:40-04:00" level=info msg="Uploading appliance.iso. Progress: 5.42%"
time="2018-04-09T10:52:43-04:00" level=info msg="Uploading appliance.iso. Progress: 5.42%"
time="2018-04-09T10:52:46-04:00" level=info msg="Uploading appliance.iso. Progress: 5.42%"
time="2018-04-09T10:52:49-04:00" level=info msg="Uploading appliance.iso. Progress: 5.42%"
time="2018-04-09T10:52:52-04:00" level=info msg="Uploading appliance.iso. Progress: 5.42%"
```

**Comment by lgayatri** [comment] 2018-04-12 06:59
The same tests are working with VIC 1.3.1 GA Build on the same environment. This is a regression  for sure. 
Please look into why appliance.iso is taking so long to get copied.

**Comment by gigawhitlocks** [comment] 2018-04-13 20:27
This issue is not seen in build # 16268, the last build before @vburenin 's merged progress bar changes.

**Comment by gigawhitlocks** [comment] 2018-04-13 20:33
Slow behavior is visible in #16280 , the first build after @vburenin 's merged progress changes. Sorry @vburenin but it looks like your change is causing this somehow..

**Comment by mdubya66** [comment] 2018-04-13 20:37
it looks like it was introduced by https://github.com/vmware/vic/pull/7320 which fixed https://github.com/vmware/vic/issues/7317

**Comment by lgayatri** [comment] 2018-04-17 10:42
I dont see the progress getting printed but the iso upload is very slow. Reopening the bug after testing with https://storage.cloud.google.com/vic-product-ova-releases/vic-v1.4.0-rc1-4516-9894ccaa.ova.

Please see the 4 minutes taken for each iso upload.
```
time="2018-04-17T06:26:52-04:00" level=info msg="  \"/Datacenter/host/Cluster\""
time="2018-04-17T06:26:52-04:00" level=info
time="2018-04-17T06:26:53-04:00" level=info msg="Creating Resource Pool \"U-VIC-0001\""
time="2018-04-17T06:26:55-04:00" level=info msg="Creating appliance on target"
time="2018-04-17T06:26:55-04:00" level=info msg="Network role \"client\" is sharing NIC with \"public\""
time="2018-04-17T06:26:55-04:00" level=info msg="Network role \"management\" is sharing NIC with \"public\""
time="2018-04-17T06:26:55-04:00" level=info msg="Creating the VCH folder"
time="2018-04-17T06:26:55-04:00" level=info msg="Creating the VCH VM"
time="2018-04-17T06:26:59-04:00" level=info msg="Uploading images for container"
time="2018-04-17T06:26:59-04:00" level=info msg="Uploading bootstrap.iso as V1.4.0-RC1-18473-657D3FE-bootstrap.iso"
time="2018-04-17T06:30:54-04:00" level=info msg="Uploading appliance.iso as V1.4.0-RC1-18473-657D3FE-appliance.iso"
time="2018-04-17T06:34:23-04:00" level=info msg="Waiting for IP information"
time="2018-04-17T06:26:52-04:00" level=info msg="  \"/Datacenter/host/Cluster\""
time="2018-04-17T06:26:52-04:00" level=info
time="2018-04-17T06:26:53-04:00" level=info msg="Creating Resource Pool \"U-VIC-0001\""
time="2018-04-17T06:26:55-04:00" level=info msg="Creating appliance on target"
time="2018-04-17T06:26:55-04:00" level=info msg="Network role \"client\" is sharing NIC with \"public\""
time="2018-04-17T06:26:55-04:00" level=info msg="Network role \"management\" is sharing NIC with \"public\""
time="2018-04-17T06:26:55-04:00" level=info msg="Creating the VCH folder"
time="2018-04-17T06:26:55-04:00" level=info msg="Creating the VCH VM"
time="2018-04-17T06:26:59-04:00" level=info msg="Uploading images for container"
time="2018-04-17T06:26:59-04:00" level=info msg="Uploading bootstrap.iso as V1.4.0-RC1-18473-657D3FE-bootstrap.iso"
time="2018-04-17T06:30:54-04:00" level=info msg="Uploading appliance.iso as V1.4.0-RC1-18473-657D3FE-appliance.iso"
time="2018-04-17T06:34:23-04:00" level=info msg="Waiting for IP information"
time="2018-04-17T06:34:38-04:00" level=info msg="Waiting for major appliance components to launch"
time="2018-04-17T06:34:38-04:00" level=info msg="Obtained IP address for client interface: \"10.197.37.133\""
time="2018-04-17T06:34:38-04:00" level=info msg="Checking VCH connectivity with vSphere target"
time="2018-04-17T06:34:38-04:00" level=info msg="vSphere API Test: https://wdc-stvc3944-146-dhcp15.eng.vmware.com vSphere API target responds as expected"
time="2018-04-17T06:37:56-04:00" level=info msg="Initialization of appliance successful"
time="2018-04-17T06:37:56-04:00" level=info
time="2018-04-17T06:37:56-04:00" level=info msg="VCH Admin Portal:"
time="2018-04-17T06:37:56-04:00" level=info msg="https://10.197.37.133:2378"
time="2018-04-17T06:37:56-04:00" level=info
time="2018-04-17T06:37:56-04:00" level=info msg="Published ports can be reached at:"
time="2018-04-17T06:37:56-04:00" level=info msg=10.197.37.133
time="2018-04-17T06:37:56-04:00" level=info
time="2018-04-17T06:37:56-04:00" level=info msg="Docker environment variables:"
time="2018-04-17T06:37:56-04:00" level=info msg="DOCKER_HOST=10.197.37.133:2376"
time="2018-04-17T06:37:56-04:00" level=info
time="2018-04-17T06:37:56-04:00" level=info msg="Environment saved in U-VIC-0001/U-VIC-0001.env"
time="2018-04-17T06:37:56-04:00" level=info
time="2018-04-17T06:37:56-04:00" level=info msg="Connect to docker:"
time="2018-04-17T06:37:56-04:00" level=info msg="docker -H 10.197.37.133:2376 --tls info"
time="2018-04-17T06:37:56-04:00" level=info msg="Installer completed successfully"

```

**Comment by vburenin** [comment] 2018-04-23 18:37
We haven't manage reliable to reproduce this issue on the same environment. 

Or findings show that in a daytime scenario VIC 1.3.1 performed a lot worse then RC version. And it is likely that VIC 1.3.1 behaved worse due to more intense parallel data upload which could easily cause significant system overload.
During night time 10pm-6am CET time everything ran successfully with no related issues.

However, we found out that we consistently get this error:
```
logs/vic-machine-output/OutputLog_46.txt:time="2018-04-21T04:17:53-05:00" level=error msg="vic-machine-linux create failed: Docker API endpoint check failed: failed to connect to https://10.197.37.179:2376/info: tls: bad certificate\n"
```

That always happens on a run number 46 and consistent in happening with VIC 1.3.1 and the latest code.

**Closed by vburenin** 2018-04-23 18:37 UTC
Labels: component/vic-engine, priority/p0, status/needs-estimation, status/needs-triage, team/lifecycle
