### ISSUE TITLE
After rebooting appliance, certificate download disappears from UI

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#821] opened 2017-09-15 11:43 UTC
**VIC Product version:**

`vic-v1.2.0-d0ea01c2.ova`

**Deployment details:**

Deployed OVA to VC on Windows. Used it for a while without difficulties. Rebooted ESXi host. After reboot, the link to download the Registry certificate has disappeared. 

![nocert](https://user-images.githubusercontent.com/16718369/30480749-a70205c6-9a1b-11e7-9325-c29922376fb7.png)

This is the second time that I have seen this behavior with the GA OVA. @corrieb saw this too with a previous deployment of mine.

**Steps to reproduce:**

Deploy OVA. Do some stuff like push/pull images to default-project, add VCH, etc. Reboot appliance.

**Actual behavior:**

Certificate download link has disappeared from **Administration** > **Configuration**.

**Expected behavior:**

Cert download link should still be there.

**Logs:**

No system logs available in **Administration** > **Logs**.

**Comment by andrewtchin** [comment] 2017-11-02 21:46
Closing as duplicate of https://github.com/vmware/harbor/issues/3527

**Closed by andrewtchin** 2017-11-02 21:46 UTC
Labels: component/admiral, component/harbor, component/ova, kind/bug, priority/medium, team/lifecycle
