### ISSUE TITLE
SSO redirects to IP instead of hostname

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic-product#815] opened 2017-09-14 19:37 UTC
When Admiral redirects to vCenter for SSO, vCenter is redirecting back to Admiral’s IP, rather than the hostname
vCenter SSO is using Admiral address which is defined when a registration towards that vCenter is made. In order host name to be used the registration when installing VIC should be done with that hostname 
https://github.com/vmware/vic-product/blob/0dc963d0427e11ef0181261c74d321a019689e76/installer/fileserver/tasks.go#L99

**Comment by anchal-agrawal** [comment] 2017-09-14 19:52
Closing as duplicate of #816.

**Closed by anchal-agrawal** 2017-09-14 19:52 UTC
