### ISSUE TITLE
Indicator in OVA to display a successful installation

### ISSUE THREAD

**Issue by karthik-narayan** [vmware/vic-product#554] opened 2017-08-10 20:09 UTC
When you log in to the OVA the first time, it is supposed to complete the vSphere Integrated Containers installation. However there is no message that indicates that this task was completed and if it was successful. 

We should have a status in the page once we log in to show that the installation was completed successfully. A stretch goal would be have a link with the installation logs / output.

**Comment by andrewtchin** [comment] 2017-08-14 16:26
@ali5ter @lweitzman Could you comment on where the success message should appear on the Getting Started page?
@karthik-narayan There aren't really logs for this and error messages should be displayed within the login modal

**Comment by karthik-narayan** [comment] 2017-08-14 17:27
If there are no logs that's fine, but I was thinking that there'd be a status icon on the top right or something that shows "Installation successful" or "Installation failed" with a "Retry" button.

**Comment by ali5ter** [comment] 2017-08-14 19:27
So right now, when you go to the 'getting started' page (hosted on port 9443 of the appliance), you will get a login prompt to continue the installation. 

After the user provides the vSphere credentials,  the last part of the installation can be done (tagging the appliance VM from what I remember). If there is a problem with this last step, then a Clarity notification should appear in the dialog if it can be caught early enough. (see image)

![screen shot 2017-08-14 at 3 25 31 pm](https://user-images.githubusercontent.com/265869/29287907-db9e4e5a-8104-11e7-8c7a-92a21a090d68.png)

If it can't, then the Clarity pattern would be to show a notification in the page.  Ref: https://vmware.github.io/clarity/documentation/alerts

When do we consider installation being complete?

I assume we don't want to show a status of successful installation every time the user comes to the getting start page. I'm not opposed to putting up a Clarity notification of successful installation after the login dialog disappears and the installation is done. This also provides the opportunity of telling the user to check out the post-installation instructions in the getting started page.

**Comment by andrewtchin** [comment] 2017-08-14 19:31
Initialization is complete after the appliance is tagged and PSC is initialized. Both of these happen after the correct vSphere creds are entered. Jason just put up a change to only show the login modal the first time

**Comment by ali5ter** [comment] 2017-08-14 19:39
Which is the way it should work. 

I'm thinking that a Clarity success notification can be used (see image)
![screen shot 2017-08-14 at 3 38 25 pm](https://user-images.githubusercontent.com/265869/29288439-bfc549de-8106-11e7-9c31-f1de1c0bd1e4.png)

**Comment by karthik-narayan** [comment] 2017-08-14 20:42
@ali5ter The clarity success notification fits the bill.

**Comment by ali5ter** [comment] 2017-08-17 19:20
Slight update to this mockup based on a conversation with @andrewtchin, @jooskim and @stuclem this morning (see image)

![screen shot 2017-08-17 at 3 18 04 pm](https://user-images.githubusercontent.com/265869/29429609-4bdffdb0-835f-11e7-9454-397dab886767.png)

The alert text should mention that vCenter Services should be restarted. The text might be linked to the section of the docs that explains this.

Ref: Specific InVision mockups at https://vmware.invisionapp.com/share/QYD37KV84

**Comment by jooskim** [comment] 2017-08-17 19:25
Looping in @cristianfalcone @jak-atx 
Thanks @ali5ter. Just to check again, there will be a button for reinitializing the plugin (and maybe retagging the OVA VM), is that correct?

**Comment by andrewtchin** [comment] 2017-08-17 19:29
@jooskim Thats in #591. I think both of these should be in 1.2 since the error messages now are not clear

**Comment by jooskim** [comment] 2017-08-17 19:35
Ok, sorry for the confusion. The services need to be restarted after the plugins have been installed successfully, and we said the automated plugin installation would come in 1.3. So putting the message now seems a bit early at this point, as it would mislead the user into believing that tagging the OVA VM requires restarting the vCenter services.

Also @ali5ter, "restart the vCenter services" could be renamed to "restart the vSphere Client services" for more clarification.

**Comment by andrewtchin** [comment] 2017-08-17 20:21
What's the dest url of the restart vSphere Client services link?

**Comment by ali5ter** [comment] 2017-08-17 20:42
after taking to @jooskim, the wording to restart vCenter services should not be in v1.2 release.
Will capture this in the v1.3 designs.

**Comment by jooskim** [comment] 2017-08-17 20:59
@andrewtchin Probably a URL to the corresponding documentation page. @stuclem please confirm if my understanding is correct.

**Comment by stuclem** [comment] 2017-08-18 08:55
@jooskim yes I think that's fine. Thanks! Do you want a link just to a doc that describes how to restart the client services? At the moment those instructions are embedded in the topics on installing/upgrading the plug-ins. Do you want me to pull those instructions into a separate topic?

**Comment by jooskim** [comment] 2017-08-18 15:31
@stuclem That would be desirable. Since restarting the vSphere Client services is a necessary step for the plugin installation, it should stand out as much as possible in the Getting Started page once it's implemented. I have been looking for some ways that do not require root access to perform the `service-control` operations on the client services, and it indeed seems possible to restart the H5 Client while inside the Flex Client (see the screenshot below), but that's unfortunately not the case for the Flex Client itself.

![image](https://user-images.githubusercontent.com/3834071/29465551-4d20f80a-83ff-11e7-8e34-44e59d053557.png)

As long as having the user logging into the VCSA to run `service-control` is not problematic I think what you already have in the plugin installation/upgrade topics could be reused.

**Comment by stuclem** [comment] 2017-08-18 16:09
@jooskim I opened https://github.com/vmware/vic-product/issues/604 to move the instructions about restarting the clients into a standalone topic.

**Comment by jak-atx** [comment] 2017-08-21 22:43
@mdubya66 For this one we will need an indication from the backend whether the VIC appliance was successfully initialized. In Andrews absence is there anyone to take this up to get into 1.2?

**Comment by mdubya66** [comment] 2017-08-22 16:32
@anchal-agrawal can you take a look

**Comment by jak-atx** [comment] 2017-08-22 17:06
@cristianfalcone please sync up with @anchal-agrawal on this thanks.

**Comment by anchal-agrawal** [comment] 2017-08-22 20:00
Needed backend changes are in #616.

**Comment by cristianfalcone** [comment] 2017-08-22 21:02
Needed frontend changes are in #619.

**Comment by jak-atx** [comment] 2017-08-22 21:14
All related PR's merged

**Closed by jak-atx** 2017-08-22 21:14 UTC
Labels: component/ova, enhancement, priority/medium

**Comment by anchal-agrawal** [comment] 2017-08-22 22:12
Didn't get a chance to verify expected behavior before PRs were merged. Verified now:

<img width="1431" alt="success-message" src="https://user-images.githubusercontent.com/4361620/29589842-93328b5a-875c-11e7-9d58-102a99adf786.png">

The alert doesn't appear upon refreshing the page and on subsequent hits, unless a re-init is performed.
