### ISSUE TITLE
Still having Plug-in issues with my vCenter 6.5 U1

### ISSUE THREAD

**Issue by vmwarelab** [vmware/vic-product#1309] opened 2018-01-11 21:48 UTC
My home lab vCenter was always being upgraded until this point. and i always had issues with having the plug-in work even with previous releases of VIC, Now with VIC 1.3 still nothing changed  and i m not ready to redeploy a new vCenter just because..  any help in trying to get this working would be awesome .. 

both type of plug-ins were installed correctly and i can see them as enabled in both type of clients. 
i also restarted both client services many numerous times 

vSphere Client 

![image](https://user-images.githubusercontent.com/19843322/34849063-1551955c-f6ef-11e7-8200-0038ac2c6080.png)

Web Client

![image](https://user-images.githubusercontent.com/19843322/34849068-209eb174-f6ef-11e7-8c85-240baf659fb4.png)

**Comment by MrVitek** [comment] 2018-01-15 19:06
I have the exact same problem. The vCenter is appliance and probably upgraded from some 6.0 release if i remember correctly.

![image](https://user-images.githubusercontent.com/35466575/34957840-8fc7ec76-fa2f-11e7-95d0-8ae949b97dac.png)

**Comment by AngieCris** [comment] 2018-01-15 22:41
@vmwarelab @MrVitek Can you provide your vCenter version and what browser are you using?

From the [doc](https://vmware.github.io/vic-product/assets/files/html/1.3/vic_vsphere_admin/plugins_vcsa.html):
> The HTML5 plug-in requires vCenter Server 6.5.0d or later. The HTML5 plug-in does not function with earlier versions of vCenter Server 6.5.0.

Also for flex-based web client:
> vSphere Integrated Containers provides a basic plug-in for the Flex-based vSphere Web Client on vCenter Server 6.0 or 6.5.

Cc: @jooskim Have we seen this before? Is it sth about VC version or browser?

**Comment by andrewtchin** [comment] 2018-01-16 04:09
@jak-atx

**Comment by MrVitek** [comment] 2018-01-16 05:22
vCenter Appliance: 6.5.0.14000 Build Number 7515524
https://docs.vmware.com/en/VMware-vSphere/6.5/rn/vsphere-vcenter-server-65u1e-release-notes.html
Browser: Tested with Chrome , IE, and Edge same result in all browsers.

**Comment by MrVitek** [comment] 2018-01-16 05:24
vCenter Appliance: 6.5.0.14000 Build Number 7515524
https://docs.vmware.com/en/VMware-vSphere/6.5/rn/vsphere-vcenter-server-65u1e-release-notes.html
Browser: Tested with Chrome , IE, and Edge same result in all browsers.

2018-01-16 5:09 GMT+01:00 Andrew Chin <notifications@github.com>:

**Comment by vmwarelab** [comment] 2018-01-16 05:34
I m running vCenter 6.5.0.13000 and its the same no matter what type of browser
I use.



Maher AlAsfar
Sr. System Engineer - SDE
Central and Eastern Canada
Solutions Engineering & Technology
Tel : 1 (416) 727-2077<tel:1%20(416)%20727-2077> | Email : malasfar@vmware.com<mailto:malasfar@vmware.com> |Blog : vmwarelab.org<http://vmwarelab.org/>

VCP5-DCV, VCP6-CMA, VCP6-NV
“I am software running in a container on top of midrange biological hardware”

Vacation Alert : <x-apple-data-detectors://4> Jan 17th - [id:image001.png@01D2C25E.7BED0150]

On Jan 16, 2018, at 12:24 AM, MrVitek <notifications@github.com<mailto:notifications@github.com>> wrote:

vCenter Appliance: 6.5.0.14000 Build Number 7515524
https://docs.vmware.com/en/VMware-vSphere/6.5/rn/vsphere-vcenter-server-65u1e-release-notes.html
Browser: Tested with Chrome , IE, and Edge same result in all browsers.

2018-01-16 5:09 GMT+01:00 Andrew Chin <notifications@github.com<mailto:notifications@github.com>>:

**Comment by vmwarelab** [comment] 2018-01-16 15:00
i have upgraded to 	
vCenter Server 6.5.0.14000 Build Number 7515524 with an embedded Platform Services Controller
Still the same problem

**Comment by jooskim** [comment] 2018-01-16 16:21
@vmwarelab We are testing the plugin on 6.5u1d (7532210) nightly and the tests pass. As @AngieCris said this signals to me the issue is with the thumbprint. FYI the Web Client (Flex Client) does not have the VIC icon in the shortcuts view, as it's an H5 Client only feature.

**Comment by vmwarelab** [comment] 2018-01-16 16:56
is there any logs i can take a look at after stopping and starting the vsphere-ui client on the vCenter appliance .

**Comment by jooskim** [comment] 2018-01-16 17:40
@vmwarelab sure, you can take a look at `/var/log/vmware/vsphere-ui/logs/vsphere_client_virgo.log`. i would recommend running grep on it as follows:

`cat /var/log/vmware/vsphere-ui/logs/vsphere_client_virgo.log | grep "ERROR"`

if you do see some error messages that say something like thumbprint doesn't match, then you hit the same issue. i know this is not the first time and it has happened on vSphere instances that were upgraded from previous versions. i am actively investigating why this keeps happening.

**Comment by vmwarelab** [comment] 2018-01-16 17:44
@jooskim  Yep

i have tons of those errors

[2018-01-16T14:59:32.557Z] [ERROR] http-bio-5090-exec-8          o.a.c.core.ContainerBase.[Catalina].[localhost].[/ui].[spring]    Servlet.service() for servlet [spring] in context with path [/ui] threw exception [Request processing failed; nested exception is com.sun.xml.internal.ws.client.ClientTransportException: HTTP transport error: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: Server certificate chain is not trusted and thumbprint doesn't match] with root cause java.security.cert.CertificateException: Server certificate chain is not trusted and thumbprint doesn't match

**Comment by jooskim** [comment] 2018-01-16 17:47
@vmwarelab Ok thanks for confirming Maher. I'll close this issue as a dupe of https://github.com/vmware/vic-ui/issues/299. Let's track this issue there.

**Closed by jooskim** 2018-01-16 17:47 UTC
Labels: kind/bug, kind/customer-found, status/need-info, status/needs-attention, team/lifecycle

**Comment by MrVitek** [comment] 2018-01-16 17:52
@jooskim  I can also confirm seeing the same error in my log.
