### ISSUE TITLE
Error(s) while trying to perform registry search (1.4RC1)

### ISSUE THREAD

**Issue by SemperFu** [vmware/vic-product#1624] opened 2018-04-19 22:00 UTC
Bug Report Basic Information
----------------------------

REQUIRED:

- vCenter Server version: 6.7
- Embedded or external PSC: Embedded
- Filename of the OVA you deployed: vic-v1.4.0-rc1-4516-9894ccaa.ova
- Does the VIC appliance recieve configuration by DHCP? Static IP
- What stage of the Appliance Lifecycle is the VIC appliance in? Running Stage
- Attach the VIC appliance support bundle : Attached. Not sure if it will show anything

Bug Report Detailed Information
-------------------------------

- What operation was being performed when the failure was noticed?
Searching for anything in the repository shows an error for the local registry.

- Provide information from the `Support Information` section of the appropriate Appliance Lifecycle stage:
Running

- Provide additional detail as necessary:

`Error(s) while trying to perform registry search: [Service https://v:8282/v2/_catalog returned error 404 for GET. id 33252 message Service not found: http://127.0.0.1/v2/_catalog]`

Browsing directly to that url I get

`{"message":"Service not found: http://127.0.0.1/v2/_catalog","statusCode":404,"documentKind":"com:vmware:xenon:common:ServiceErrorResponse","errorCode":-2147483648}`

![s1](https://user-images.githubusercontent.com/1786698/39020579-710af13c-43fb-11e8-97bb-19bca3d0eeae.PNG)
[container-logs.zip](https://github.com/vmware/vic-product/files/1929908/container-logs.zip)

**Comment by shadjiiski** [comment] 2018-04-20 08:59
Could you also provide the admiral logs (`/storage/log/admiral` directory on OVA machine) and the contents of the `/storage/data/admiral/custom.conf` file (again on the OVA machine)? Please leave a note, if you obfuscate any addresses/hostnames

**Comment by SemperFu** [comment] 2018-04-20 16:13
@gmcelhoe I did not add any registries but didn't have any errors searching before 1.4RC1. My searches work fine but figure I'd report it.

@shadjiiski I have attached the log and conf unmodified. Just zipped them up.

[VMware.zip](https://github.com/vmware/vic-product/files/1932803/VMware.zip)

**Comment by shadjiiski** [comment] 2018-04-23 09:14
@SemperFu thanks for the reply! Your configuration seems to be messed up - the `harbor.tab.url` property in your `custom.conf` file points to the address of your Admiral (Management Portal) instance `https://{your-hostname}:8282`. It should be set to whatever the address of your Harbor (Container Registry) instance is - probably `https://{your-hostname}:443`

When you installed the OVA, did you do any additional configuration during the "Customize template" step of the "Deploy OVF Template" workflow? I'm interested in whether you have changed the default Registry port from 443 to 8282. If not, then there probably is an issue with the installer (though I deployed the same OVA with defaults and could not reproduce the issue) cc @andrewtchin

**Comment by andrewtchin** [comment] 2018-04-23 15:33
@shadjiiski The canonical way to gather logs from the VIC appliance is the appliance support bundle - please let me know if there are additional files that need to be gathered by this script - https://github.com/vmware/vic-product/blob/master/installer/docs/SUPPORT.md#appliance-support-bundle
@SemperFu depending on your answer to @shadjiiski and if this still needs investigation, please provide the appliance support bundle - this is different from the container log bundle in your original post

**Comment by SemperFu** [comment] 2018-04-23 17:14
@shadjiiski I didn't modify anything in the installer. I believe the only difference from previous was using HTML5 vs the Web client for deploying it. I don't really have anything on it. I'll try and redeploy it today to see if it still does it.

**Comment by SemperFu** [comment] 2018-04-23 17:36
@shadjiiski The default registry port has always been 8282 from from the OVA for 1.3 and 1.4 in the installer. If this is supposed to be 443 then the installer should be changed.
![image](https://user-images.githubusercontent.com/1786698/39143220-363f1a6c-46fb-11e8-95d7-51764976aef8.png)

**Comment by andrewtchin** [comment] 2018-04-23 18:47
@SemperFu the HTML5 client is not supported for deploying the VIC appliance. If you used the HTML5 client, please redeploy following the documentation.

https://vmware.github.io/vic-product/assets/files/html/1.3/vic_vsphere_admin/deploy_vic_appliance.html

> Use the Flex-based vSphere Web Client to deploy the appliance. You cannot deploy OVA files from the HTML5 vSphere Client or from the legacy Windows client.

**Comment by SemperFu** [comment] 2018-04-23 20:12
@andreiw Yeah that seems to be it. I've been redeploying it over and over for different things I didn't think about the client. That said, changing the port to 443 on HTML5 and it seems to deploy and work the same as deployment on Flex.

**Comment by morris-jason** [comment] 2018-04-24 16:26
The root cause of this problem has been fixed in #1642, but please continue to refer to [the vSphere documantation](https://docs.vmware.com/en/VMware-vSphere/6.5/rn/vsphere-client-65-html5-functionality-support.html) for supported ovf operations in the html5 client.

**Closed** 2018-04-24 16:51 UTC
Labels: component/ova, kind/customer-found, team/lifecycle
