### ISSUE TITLE
Update the title for the OVA login page

### ISSUE THREAD

**Issue by karthik-narayan** [vmware/vic-product#553] opened 2017-08-10 20:07 UTC
It currently says "Complete VIC appliance installation" even when you are logging in for the second time. 

It should instead just say "Login". The sub text can say "The first time you log in, the system will complete the VIC installation" 

![image](https://user-images.githubusercontent.com/13806150/29189738-7ba58ea4-7dcc-11e7-85aa-d6a892a5bbe0.png)

**Comment by andrewtchin** [comment] 2017-08-10 20:10
Classifying this as duplicate of #484

**Closed by andrewtchin** 2017-08-10 20:10 UTC
Labels: component/ova
