### ISSUE TITLE
Admiral service fails to start due to "publicUri should be a non empty absolute URI"

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-product#528] opened 2017-08-07 08:30 UTC
Cred: root/Admin!23

Build: vic-4efc2f2e-dev.ova
Admiral service fails to start . 
Initialization Args being passed :   --sandbox=/var/admiral/  --publicUri=https://:8282/ --bindAddress=0.0.0.0 --port=-1

Aug 07 08:21:36 vic-st-h2-132.eng.vmware.com start_admiral.sh[934]: + JAVA_OPTS='-Dconfiguration.properties=/configs/config.properties -Ddcp.net.ssl.trustStore=/configs/trustedcertificates.jks -Ddc
p.net.ssl.trustStorePassword=changeit -Xmx768M -Xms768M -Xss256K -Xmn256M -XX:MaxMetaspaceSize=256m -XX:+HeapDumpOnOutOfMemoryError'
Aug 07 08:21:36 vic-st-h2-132.eng.vmware.com start_admiral.sh[934]: + PID=5
Aug 07 08:21:36 vic-st-h2-132.eng.vmware.com start_admiral.sh[934]: + wait 5
Aug 07 08:21:36 vic-st-h2-132.eng.vmware.com start_admiral.sh[934]: + java -Dconfiguration.properties=/admiral/config/dist_configuration.properties -Dconfiguration.properties=/configs/config.proper
ties -Ddcp.net.ssl.trustStore=/configs/trustedcertificates.jks -Ddcp.net.ssl.trustStorePassword=changeit -Xmx768M -Xms768M -Xss256K -Xmn256M -XX:MaxMetaspaceSize=256m -XX:+HeapDumpOnOutOfMemoryErro
r -cp '/admiral/*:/admiral/lib/*:/etc/xenon/dynamic-services/*' -Dservice.document.version.retention.limit=50 -Dservice.document.version.retention.floor=10 com.vmware.admiral.host.ManagementHost --
bindAddress=0.0.0.0 --port=-1 --sandbox=/var/admiral/ --publicUri=https://:8282/ --bindAddress=0.0.0.0 --port=-1 --authConfig=/configs/psc-config.properties --securePort=8282 --keyFile=/configs/ser
ver.key --certificateFile=/configs/server.crt --startMockHostAdapterInstance=false
Aug 07 08:21:36 vic-st-h2-132.eng.vmware.com start_admiral.sh[934]: Aug 07, 2017 8:21:36 AM http://127.0.0.1:0 initializeHostAndServices
Aug 07 08:21:36 vic-st-h2-132.eng.vmware.com start_admiral.sh[934]: INFO: Initializing ...
Aug 07 08:21:36 vic-st-h2-132.eng.vmware.com start_admiral.sh[934]: [1][W][2017-08-07T08:21:36.625Z][1][Utils][logWarning][Using provider 'com.vmware.admiral.auth.idm.local.LocalAuthConfigProvider'
.]
Aug 07 08:21:36 vic-st-h2-132.eng.vmware.com start_admiral.sh[934]: [2][W][2017-08-07T08:21:36.633Z][1][Utils][logWarning][Using provider 'com.vmware.admiral.auth.idm.psc.PscAuthConfigProvider'.]
Aug 07 08:21:36 vic-st-h2-132.eng.vmware.com start_admiral.sh[934]: [3][W][2017-08-07T08:21:36.635Z][1][Utils][logWarning][Using provider 'com.vmware.admiral.auth.idm.local.LocalAuthConfigProvider'
.]
Aug 07 08:21:36 vic-st-h2-132.eng.vmware.com start_admiral.sh[934]: [4][W][2017-08-07T08:21:36.635Z][1][Utils][logWarning][Using provider 'com.vmware.admiral.auth.idm.psc.PscAuthConfigProvider'.]
Aug 07 08:21:36 vic-st-h2-132.eng.vmware.com start_admiral.sh[934]: Exception in thread "main" java.lang.IllegalArgumentException: publicUri should be a non empty absolute URI
Aug 07 08:21:36 vic-st-h2-132.eng.vmware.com start_admiral.sh[934]: at com.vmware.xenon.common.ServiceHost.initialize(ServiceHost.java:668)
Aug 07 08:21:36 vic-st-h2-132.eng.vmware.com start_admiral.sh[934]: at com.vmware.xenon.common.ServiceHost.initialize(ServiceHost.java:631)
Aug 07 08:21:36 vic-st-h2-132.eng.vmware.com start_admiral.sh[934]: at com.vmware.admiral.host.ManagementHost.initialize(ManagementHost.java:199)
Aug 07 08:21:36 vic-st-h2-132.eng.vmware.com start_admiral.sh[934]: at com.vmware.admiral.host.ManagementHost.initializeHostAndServices(ManagementHost.java:154)
Aug 07 08:21:36 vic-st-h2-132.eng.vmware.com start_admiral.sh[934]: at com.vmware.admiral.host.ManagementHost.main(ManagementHost.java:125)
Aug 07 08:21:36 vic-st-h2-132.eng.vmware.com systemd[1]: admiral.service: Main process exited, code=exited, status=1/FAILURE
Aug 07 08:21:36 vic-st-h2-132.eng.vmware.com docker[1026]: vic-admiral
Aug 07 08:21:36 vic-st-h2-132.eng.vmware.com docker[1044]: vic-admiral
Aug 07 08:21:36 vic-st-h2-132.eng.vmware.com systemd[1]: admiral.service: Unit entered failed state.
Aug 07 08:21:36 vic-st-h2-132.eng.vmware.com systemd[1]: admiral.service: Failed with result 'exit-code'.

**Comment by andrewtchin** [comment] 2017-08-07 13:25
This should be closed as not a bug. 
PSC registration was not performed through the Getting Started page and user manually attempted to start Admiral without proper initialization

**Closed by andrewtchin** 2017-08-07 13:25 UTC

**Comment by lgayatri** [comment] 2017-08-08 07:02
After redeployment of OVA, I logged in :9443 and entered VCSA IP and cred. Got the Getting started page in couple of seconds
![image](https://user-images.githubusercontent.com/25006749/29059278-6b2a965a-7c32-11e7-9de1-2ac28c799f6c.png)
Waited for 20 minutes and checked :8282 
![image](https://user-images.githubusercontent.com/25006749/29059604-024c29e4-7c34-11e7-951f-88efe3490b11.png)
Please feel free to access the setup Live with usual creds
