### ISSUE TITLE
Management Portal redirection is broken

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-product#988] opened 2017-10-26 10:47 UTC
Build: https://storage.googleapis.com/vic-product-ova-builds/vic-2161-v1.2.0-rc1-132-g89afccc.ova
Please see the highlighted text in the screenshot 

![image](https://user-images.githubusercontent.com/25006749/32048779-41a57984-ba68-11e7-9509-046a84bb45cc.png)

Three highlights.
a. IP address on OVA running on 9443
b. open is selected
c. IP address to which the page would redirect.

![image](https://user-images.githubusercontent.com/25006749/32048649-d508d3ac-ba67-11e7-8a97-d258e202b341.png)
The redirection will fail.

10.197.36.217 comes from the Welcome screen of OVA. This issue is being tracked -
 https://github.com/vmware/vic-product/issues/977.
The redirection URL should be corrected to pick the actual OVA IP.
![image](https://user-images.githubusercontent.com/25006749/32048949-d81948b4-ba68-11e7-9104-26eb8bee620c.png)

**Comment by andrewtchin** [comment] 2017-10-26 14:38
This is probably a duplicate of #977 since the appliance determines the IP and then uses it here

**Closed by andrewtchin** 2017-10-26 14:38 UTC
