### ISSUE TITLE
Failed to locate productVM, trusted content is not available

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-product#732] opened 2017-09-05 08:17 UTC
OVA: https://storage.googleapis.com/vic-product-ova-builds/vic-v1.2.0-rc2-b53a69aa.ova

Despite successful registration, I am seeing
![image](https://user-images.githubusercontent.com/25006749/30051246-e481b4b2-923e-11e7-99a6-0fb548c6e65f.png)

journalctl says:

Sep 05 08:13:58 vic-st-h2-132.eng.vmware.com start_admiral.sh[825]: [185][W][2017-09-05T08:13:58.311Z][22][ServerX509TrustManager][handleRequest][No document links for operation PATCH https://172.17.0.2:8282/core/callbacks/32f0379d7f5c00755586ccf20ecb8 2191 https://10.197.37.132:8282/core/local-query-tasks/86738246-3198-4e6e-8dea-28eddf180b10 [subject] /core/authz/system-user]
Sep 05 08:13:58 vic-st-h2-132.eng.vmware.com start_admiral.sh[825]: [186][W][2017-09-05T08:13:58.323Z][12][8282/][lambda$verifyTokenInternal$38][Error verifying token: java.lang.IllegalStateException: SsoManager has not been initialized]
Sep 05 08:13:58 vic-st-h2-132.eng.vmware.com start_admiral.sh[825]: [187][I][2017-09-05T08:13:58.323Z][12][8282/][lambda$verifyTokenInternal$38][Retrying token verification with basic auth.]
Sep 05 08:13:58 vic-st-h2-132.eng.vmware.com start_admiral.sh[825]: [188][W][2017-09-05T08:13:58.324Z][12][8282/core/authn/basic][handleTokenVerify][Error verifying token: Separator for header not found]
Sep 05 08:13:58 vic-st-h2-132.eng.vmware.com start_admiral.sh[825]: [189][W][2017-09-05T08:13:58.324Z][12][8282/][lambda$verifyTokenInternal$38][Error verifying token: com.vmware.xenon.common.jwt.Verifier$InvalidTokenException: Separator for header not found]
Sep 05 08:13:58 vic-st-h2-132.eng.vmware.com bash[999]: {"message":"Service not found: http://127.0.0.1/projects/default-project","statusCode":404,"documentKind":"com:vmware:xenon:common:ServiceErrorResponse","errorCode":-2147483648}
Sep 05 08:13:58 vic-st-h2-132.eng.vmware.com bash[999]: add_default_users added project-admin
Sep 05 08:13:58 vic-st-h2-132.eng.vmware.com systemd[1]: Started Admiral Default Users.
Sep 05 08:13:58 vic-st-h2-132.eng.vmware.com systemd[1]: Starting PSC Get Token...
...

**Comment by andrewtchin** [comment] 2017-09-05 20:55
@lgayatri It's not clear what's going on here. Please provide information necessary for us to reproduce or access the environment.

**Comment by lgayatri** [comment] 2017-09-06 06:16
@andrewtchin , I have live test bed at 10.197.37.132- root/Admin!23
After deploying the OVA, I registered it with a 6.5U1 GA VC and observed this message.
VC: 10.133.146.15- administrator@vsphere.local/Admin!23

**Comment by andrewtchin** [comment] 2017-09-06 17:09
Based on the logs this looks like an Admiral issue @sergiosagu 
PSC files are populated but logs in `journalctl -u admiral` show the above errors

**Comment by lcastellano** [comment] 2017-09-06 17:13
The error reported in the logs is generated when an access to Admiral is performed before the SSO has been initialized. SSO initialization can take a few seconds, it requires some credential exchanges with the PSC. It take longer if the location of the PSC is remote. This should be a temporary condition and should go away after the SSO component in Admiral has been initialized.

**Comment by lgayatri** [comment] 2017-09-06 17:19
I am not seeing it going by itself. If I refresh the web page then I will be prompted for re-registration and cannot even close the registration window.

**Comment by lcastellano** [comment] 2017-09-06 17:29
I m not sure what you should see in the UI, my comment is about the error condition reported by Admiral. Can you please attach the full Admiral logs? Thanks.

**Comment by lgayatri** [comment] 2017-09-06 17:33
Please feel free to access 10.197.37.132- root/Admin!23 for admiral logs. This IP is of the current OVA.

**Comment by andrewtchin** [comment] 2017-09-06 18:21
Looks like the logs from Sept 5 are gone

**Comment by andrewtchin** [comment] 2017-09-06 18:37
The reason the modal shows up again on the Getting Started Page is because if there are any errors (which includes the Failed to locate ProductVM error), we do not write the file we use to determine that initialization was successful.

**Comment by fd025270** [comment] 2017-09-28 13:07
Hi,
I have deployed vic 1.2 and tryed to register with external PSC.

No error when executing the jar file to register with PSC, but when i try to start on port 8282, i have the same issue :

> {"message":"SsoManager has not been 

> initialized"

And the journal says : 
`Sep 28 13:00:28 a203pvw108.mousquetaires.com start_admiral.sh[593]: at com.vmware.admiral.auth.idm.psc.saml.util.SamlManager.getInstance(SamlManager.java:100)
Sep 28 13:00:28 a203pvw108.mousquetaires.com start_admiral.sh[593]: at com.vmware.admiral.auth.idm.psc.saml.sso.authentication.SamlRequestSender.<init>(SamlRequestSender.java:45)
Sep 28 13:00:28 a203pvw108.mousquetaires.com start_admiral.sh[593]: at com.vmware.admiral.auth.idm.psc.saml.util.SsoUriGenerator.generateRedirectUrl(SsoUriGenerator.java:47)
Sep 28 13:00:28 a203pvw108.mousquetaires.com start_admiral.sh[593]: at com.vmware.admiral.auth.idm.psc.service.PscAuthenticationService.redirectToSamlSso(PscAuthenticationService.java:423)
Sep 28 13:00:28 a203pvw108.mousquetaires.com start_admiral.sh[593]: at com.vmware.admiral.auth.idm.psc.service.PscAuthenticationService.redirectToSso(PscAuthenticationService.java:400)
Sep 28 13:00:28 a203pvw108.mousquetaires.com start_admiral.sh[593]: at com.vmware.admiral.auth.idm.psc.service.PscAuthenticationService.handleGet(PscAuthenticationService.java:383)
Sep 28 13:00:28 a203pvw108.mousquetaires.com start_admiral.sh[593]: at com.vmware.xenon.common.StatelessService.handleRequest(StatelessService.java:120)
Sep 28 13:00:28 a203pvw108.mousquetaires.com start_admiral.sh[593]: at com.vmware.xenon.common.StatelessService.handleRequest(StatelessService.java:103)
Sep 28 13:00:28 a203pvw108.mousquetaires.com start_admiral.sh[593]: at com.vmware.xenon.common.ServiceHost.lambda$queueOrScheduleRequestInternal$44(ServiceHost.java:4197)
Sep 28 13:00:28 a203pvw108.mousquetaires.com start_admiral.sh[593]: at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
Sep 28 13:00:28 a203pvw108.mousquetaires.com start_admiral.sh[593]: at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
Sep 28 13:00:28 a203pvw108.mousquetaires.com start_admiral.sh[593]: at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
Sep 28 13:00:28 a203pvw108.mousquetaires.com start_admiral.sh[593]: at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
Sep 28 13:00:28 a203pvw108.mousquetaires.com start_admiral.sh[593]: at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Sep 28 13:00:28 a203pvw108.mousquetaires.com start_admiral.sh[593]: ]
Sep 28 13:00:29 a203pvw108.mousquetaires.com start_admiral.sh[593]: [234][I][2017-09-28T13:00:29.647Z][12][8282/][lambda$schedulePeriodicCertificatesReload$1][Host https://10.117.0.108:8282/: reloading all certificates]
Sep 28 13:01:29 a203pvw108.mousquetaires.com start_admiral.sh[593]: [235][I][2017-09-28T13:01:29.650Z][12][8282/][lambda$schedulePeriodicCertificatesReload$1][Host https://10.117.0.108:8282/: reloading all certificates]
Sep 28 13:01:33 a203pvw108.mousquetaires.com start_admiral.sh[593]: [236][I][2017-09-28T13:01:33.271Z][19][8282/resources/epz-periodic-enumeration][doTrigger][Periodic refresh]
Sep 28 13:02:29 a203pvw108.mousquetaires.com start_admiral.sh[593]: [237][I][2017-09-28T13:02:29.651Z][19][8282/][lambda$schedulePeriodicCertificatesReload$1][Host https://10.117.0.108:8282/: reloading all certificates]
Sep 28 13:03:29 a203pvw108.mousquetaires.com start_admiral.sh[593]: [238][I][2017-09-28T13:03:29.654Z][19][8282/][lambda$schedulePeriodicCertificatesReload$1][Host https://10.117.0.108:8282/: reloading all certificates]
Sep 28 13:04:29 a203pvw108.mousquetaires.com start_admiral.sh[593]: [239][I][2017-09-28T13:04:29.654Z][19][8282/][lambda$schedulePeriodicCertificatesReload$1][Host https://10.117.0.108:8282/: reloading all certificates]
Sep 28 13:05:20 a203pvw108.mousquetaires.com start_admiral.sh[593]: [240][W][2017-09-28T13:05:20.753Z][91][8282/auth/psc/callback][redirectToSamlSso][Could not generate redirect URL: java.lang.IllegalStateException: SsoManager has not be
en initialized
Sep 28 13:05:20 a203pvw108.mousquetaires.com start_admiral.sh[593]: at com.vmware.admiral.auth.idm.psc.saml.util.SamlManager.getInstance(SamlManager.java:100)
Sep 28 13:05:20 a203pvw108.mousquetaires.com start_admiral.sh[593]: at com.vmware.admiral.auth.idm.psc.saml.sso.authentication.SamlRequestSender.<init>(SamlRequestSender.java:45)
Sep 28 13:05:20 a203pvw108.mousquetaires.com start_admiral.sh[593]: at com.vmware.admiral.auth.idm.psc.saml.util.SsoUriGenerator.generateRedirectUrl(SsoUriGenerator.java:47)
Sep 28 13:05:20 a203pvw108.mousquetaires.com start_admiral.sh[593]: at com.vmware.admiral.auth.idm.psc.service.PscAuthenticationService.redirectToSamlSso(PscAuthenticationService.java:423)
Sep 28 13:05:20 a203pvw108.mousquetaires.com start_admiral.sh[593]: at com.vmware.admiral.auth.idm.psc.service.PscAuthenticationService.redirectToSso(PscAuthenticationService.java:400)
Sep 28 13:05:20 a203pvw108.mousquetaires.com start_admiral.sh[593]: at com.vmware.admiral.auth.idm.psc.service.PscAuthenticationService.handleGet(PscAuthenticationService.java:383)
Sep 28 13:05:20 a203pvw108.mousquetaires.com start_admiral.sh[593]: at com.vmware.xenon.common.StatelessService.handleRequest(StatelessService.java:120)
Sep 28 13:05:20 a203pvw108.mousquetaires.com start_admiral.sh[593]: at com.vmware.xenon.common.StatelessService.handleRequest(StatelessService.java:103)
Sep 28 13:05:20 a203pvw108.mousquetaires.com start_admiral.sh[593]: at com.vmware.xenon.common.ServiceHost.lambda$queueOrScheduleRequestInternal$44(ServiceHost.java:4197)
Sep 28 13:05:20 a203pvw108.mousquetaires.com start_admiral.sh[593]: at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
Sep 28 13:05:20 a203pvw108.mousquetaires.com start_admiral.sh[593]: at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
Sep 28 13:05:20 a203pvw108.mousquetaires.com start_admiral.sh[593]: at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
Sep 28 13:05:20 a203pvw108.mousquetaires.com start_admiral.sh[593]: at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
Sep 28 13:05:20 a203pvw108.mousquetaires.com start_admiral.sh[593]: at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Sep 28 13:05:20 a203pvw108.mousquetaires.com start_admiral.sh[593]: ]
Sep 28 13:05:29 a203pvw108.mousquetaires.com start_admiral.sh[593]: [241][I][2017-09-28T13:05:29.657Z][19][8282/][lambda$schedulePeriodicCertificatesReload$1][Host https://10.117.0.108:8282/: reloading all certificates]
Sep 28 13:06:29 a203pvw108.mousquetaires.com start_admiral.sh[593]: [242][I][2017-09-28T13:06:29.661Z][19][8282/][lambda$schedulePeriodicCertificatesReload$1][Host https://10.117.0.108:8282/: reloading all certificates]
Sep 28 13:06:33 a203pvw108.mousquetaires.com start_admiral.sh[593]: [243][I][2017-09-28T13:06:33.552Z][12][8282/resources/epz-periodic-enumeration][doTrigger][Periodic refresh]
root@a203pvw108 [ ~ ]#
`

**Comment by andrewtchin** [comment] 2017-09-28 15:44
Hi @fd025270 did you receive the red error bar on the Getting Started Page like in the top screenshot in this issue? Or did you receive a green bar on the Getting Started Page?
When you say "No error when executing the jar file to register with PSC" were you manually running the jar file according to our troubleshooting topic? If so, could you provide the command you executed?

**Comment by lgayatri** [comment] 2017-09-28 17:32
@fd025270 , do see https://github.com/vmware/admiral/issues/132 and try to re-register PSC

**Comment by andrewtchin** [comment] 2017-09-28 19:32
Also @fd025270 If you access the Admiral interface too quickly after registering you will see this message in your web browser, though I'm not sure if this is the same scenario as you are experiencing. Please wait a minute after getting the green bar on the Getting Started Page before attempting to access Admiral if this is the case.
```
{"message":"SsoManager has not been initialized","stackTrace":["com.vmware.admiral.auth.idm.psc.saml.util.SamlManager.getInstance(SamlManager.java:100)","com.vmware.admiral.auth.idm.psc.saml.sso.authentication.SamlRequestSender.<init>(SamlRequestSender.java:45)","com.vmware.admiral.auth.idm.psc.saml.util.SsoUriGenerator.generateRedirectUrl(SsoUriGenerator.java:47)","com.vmware.admiral.auth.idm.psc.service.PscAuthenticationService.redirectToSamlSso(PscAuthenticationService.java:426)","com.vmware.admiral.auth.idm.psc.service.PscAuthenticationService.redirectToSso(PscAuthenticationService.java:403)","com.vmware.admiral.auth.idm.psc.service.PscAuthenticationService.handleGet(PscAuthenticationService.java:386)","com.vmware.xenon.common.StatelessService.handleRequest(StatelessService.java:120)","com.vmware.xenon.common.StatelessService.handleRequest(StatelessService.java:103)","com.vmware.xenon.common.ServiceHost.lambda$queueOrScheduleRequestInternal$44(ServiceHost.java:4197)","java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)","java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)","java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)","java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)","java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)"],"statusCode":500,"documentKind":"com:vmware:xenon:common:ServiceErrorResponse","errorCode":0}
```

**Comment by fd025270** [comment] 2017-09-29 07:28
Thanks for all your answer, i will try now

**Comment by fd025270** [comment] 2017-09-29 11:55
Ok , so , first, thanks @andrewtchin and @lgayatri 
I made a misconfiguration during the OVA configuration : wrong nameserver cause unable to ping the PSC.
I did some modification in the resolv.conf, but not a good idea

Redeployed from scratched and now it's fine

Thanks

**Comment by lgayatri** [comment] 2017-09-29 11:56
@fd025270 Welcome! Glad to know that its working fine.

**Comment by lgayatri** [comment] 2017-11-14 06:52
I have not seen this issue recently.

**Comment by andrewtchin** [comment] 2017-11-14 15:22
Thanks @lgayatri I also have not reproduced this. Closing and we can reopen if we see it.

**Closed by andrewtchin** 2017-11-14 15:22 UTC
Labels: priority/medium, status/need-info, team/lifecycle
